apiVersion: v1
kind: ConfigMap
metadata:
  name: go-web-example-config
  namespace: default
data:
  config.yaml: |
    server:
      serverName: go-server-rest-api
      port: 8080
      host: 0.0.0.0
      version: v1.0.0

    etcd:
      enable: true
      host: etcd-service
      port: 2379
      dialTimeOut: 5
      leaseTTL: 60
      maxRetries: 3
      retryInterval: 1
      healthCheck:
        enable: true
        interval: 10

    mysql:
      host: mysql-service
      port: 3306
      username: root
      password: ${MYSQL_PASSWORD}
      database: example
      maxOpenConns: 100
      maxIdleConns: 10
      connMaxLifetime: 3600

    redis:
      host: redis-service
      port: 6379
      password: ${REDIS_PASSWORD}
      db: 0
      poolSize: 10

    mongodb:
      uri: mongodb://mongodb-service:27017
      database: example
      maxPoolSize: 100
      minPoolSize: 10

    kafka:
      brokers:
        - kafka-service:9092
      topic: example
      group: example-group
      maxMessageBytes: 1048576 